[package]
name = "auracite"
version = "0.1.0"
authors = ["berwyn <berwyn.codeweaver@gmail.com>"]

[dependencies]
hyper = "0.10.4"
rocket = "0.2.2"
rocket_codegen = "0.2.2"
select = "0.3.0"
xml-rs = "0.4.0"
